# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_card_number', models.CharField(max_length=64)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), (None, 'Select Gender')], max_length=32)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('id_card_number', models.CharField(max_length=64)),
                ('guardian', models.CharField(max_length=100)),
                ('guardian_adress', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=32)),
                ('guardian_email', models.CharField(blank=True, max_length=100, null=True)),
                ('school_origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='Registree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.Registration'),
        ),
        migrations.AddField(
            model_name='admission',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Batch'),
        ),
        migrations.AddField(
            model_name='admission',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.ClassLevel'),
        ),
        migrations.AddField(
            model_name='admission',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.Department'),
        ),
    ]
