# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:10
from __future__ import unicode_literals

import admission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_auto_20170807_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='student_card_number',
            field=models.CharField(default=admission.models.student_number, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(default=admission.models.registration_number, editable=False, max_length=20, unique=True),
        ),
    ]
