# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=16)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('adress_1', models.CharField(max_length=200)),
                ('adress_2', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('fax', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('authorization_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
