# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='classLevel',
            new_name='class_level',
        ),
    ]
